### ISSUE TITLE
Додати функцію отримання списку предметів в певному семестрі

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#11]

**Comment by gzaspa** [comment]
Тут потрібно трошки змінити завдання - отримувати всіпредмети для певної групи

**Comment by SashaKononenko** [comment]
Тобто прибрати фільтрацію за семестром?

**Comment by gzaspa** [comment]
Так. І виправити URL в контролері, відповідно.

**Comment by SashaKononenko** [comment]
Це робити в новій віткі?

**Comment by gzaspa** [comment]
Ні в якому разі. team2 вже немає. Потрібно зробити нову гілку, виправити, перевірити і змерджити.

**Comment by SashaKononenko** [comment]
ну я це і мав наувазі

**Comment by gzaspa** [comment]
ок, тоді я неправильно зрозумів, працюйте.

**Comment by SashaKononenko** [comment]
![image](https://user-images.githubusercontent.com/22222011/36999853-1cacf17a-20ca-11e8-80fd-655c3ce05b2f.png)
В мене проблемка з назвами, якщо прибрати фільтрацію по семестру то виходить що назви URL і методу повторюються

**Comment by gzaspa** [comment]
Закрито як застарілий. Доопрацює інша команда.
