### ISSUE TITLE
Працівник деканату може додавати, редагувати та видаляти групи (епік #12)

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#127]
Зробити за аналогією з вікном спеціалізацій.
При видаленні групи перевіряти, чи є в даній групі активні студенти; якщо є, не давати змоги видалити

**Comment by volodymyr-polishchuk** [comment]
Переглянувши код, я знайшов уже існуючу реалізацію цих дій. Їх можна знайти:
Додавання груп `GroupController:114`
Редагування груп `GroupController:154`
Видалення груп `GroupController:176`
