### ISSUE TITLE
Звіт про успішність студентів у відсотках оцінок

### ISSUE THREAD

**Issue by ValentynTulub** [chdtu-fitis/deanoffice-backend#13]
Додати функцію формування звіту про успішність студентів певної групи у % оцінок.
Звіт повинен бути у вигляді docx файлу, що містить таблицю, рядками якої будуть студенти, а стовпчиками кількість певних оцінок у % від загальної кількості (3, 4, 5; A, B, C, D, E). Для цифр і ECTS відсотки розраховуються окремо.

**Comment by gzaspa** [comment]
Зроблено.
