### ISSUE TITLE
Працівник деканату може сформувати документ з переліком предметів для випускних груп (епік #15)

### ISSUE THREAD

**Issue by volodymyr-polishchuk** [chdtu-fitis/deanoffice-backend#138]
Приклад документу, що має формуватися:
[example.pdf](https://github.com/chdtu-fitis/deanoffice-backend/files/2548094/example.pdf)

**Comment by volodymyr-polishchuk** [comment]
Приклад згенерованого документа:
[101 05-11-2018 19-32.pdf](https://github.com/chdtu-fitis/deanoffice-backend/files/2549863/101.05-11-2018.19-32.pdf)

**Comment by gzaspa** [comment]
Ще в 8 семестрі групі потрібно поставити Бакалаврську роботу з видом контролю підсумкова атестація і перевірити, чи це ставитиме в кінець. Крім того, диференційований залік не повинен бути окремо, але потрібно вияснити, в який розділ його поставити

**Comment by volodymyr-polishchuk** [comment]
Весь список формується на основі CourseForGroups. Якби там був CourseForGroup з формою контролю Бакалаврська робота, то воно б його добавило. Для тестування я не вибирав випускну групу, тому, напевно, і відсутня Бакалаврська робота.
З приводу сортування, бажано б дізнатися повний порядок, що за чим має іти.

**Comment by gzaspa** [comment]
Диференційований залік нехай так залишається. Стосовно тестування, краще це робити на випускних групах, тому що саме для них це робиться.
