### ISSUE TITLE
Чи потрібно виконувати об'єднання оцінок для багатосеместрових диспиплін у #13?

### ISSUE THREAD

**Issue by ValentynTulub** [chdtu-fitis/deanoffice-backend#14]

**Comment by ValentynTulub** [comment]
[#13](https://github.com/chdtu-fitis/deanoffice-backend/issues/13)

**Comment by ValentynTulub** [comment]
Я, здається, зрозумів. Багатосеместрові дисципліни тут не є особливими, оскліьки цей звіт містить дані за один семестр, я правий?

**Comment by gzaspa** [comment]
Ні, аж ніяк, якщо подивитись на запити, то за всі семестри, менші за 8 чи 10.

**Comment by gzaspa** [comment]
Беремо проценти просто всіх оцінок, не об'єднуємо.
