### ISSUE TITLE
Працівник деканату може бачити дані, на основі яких може приймати рішення про призначення студентам стипендії

### ISSUE THREAD

**Issue by volodymyr-polishchuk** [chdtu-fitis/deanoffice-backend#172]
Потрібно на Backend`і сформувати інформацію, яка вказуватиме на те, які студенти мають заборгованості і який середній бал студентів, що не мають заборгованостей.
![image](https://user-images.githubusercontent.com/16689707/50441645-61646780-0904-11e9-9967-271ff3c0440e.png)
В таблиці мають бути всі студенти, але в ті, що мають заборгованість, повинні бути виділені червоним кольором і в них не повинно бути середнього балу, Додатково для таких студентів має вказуватися перелік предметів, які вони не здали.

**Comment by gzaspa** [comment]
You can do something like

@NamedQuery(name="IssueDescriptor.findByIssueDescriptorId" ,

    query=" select new com.test.live.dto.IssuesDto (idc.id, dep.department, iss.issueName, 
               cat.issueCategory, idc.issueDescriptor, idc.description) 
            from Department dep 
            inner join dep.issues iss 
            inner join iss.category cat 
            inner join cat.issueDescriptor idc 
            where idc.id in(?1)")
And there must be Constructor like

public IssuesDto(long id, String department, String issueName, String issueCategory, String issueDescriptor,
            String description) {
        super();
        this.id = id;
        this.department = department;
        this.issueName = issueName;
        this.issueCategory = issueCategory;
        this.issueDescriptor = issueDescriptor;
        this.description = description;
    }

**Comment by volodymyr-polishchuk** [comment]
@gzaspa Наскільки я розумію це вже в master?

**Comment by gzaspa** [comment]
Так, там багато вже зроблено, але не до кінця
