### ISSUE TITLE
В сформованій академдовідці, якщо в студента немає жодного зданого предмету, повинна відображатись відповідна інформація в таблиці оцінок

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#173]
В сформованій академдовідці, якщо в студента немає жодного зданого предмету, повинна відображатись відповідна інформація в таблиці оцінок, а саме під рядком шапки таблиці повинен бути рядок, в якому написано: "Заліків та іспитів не здавав. No credits and exams."

**Comment by SashaKononenko** [comment]
Я правильно розумію що замість 
![image](https://user-images.githubusercontent.com/22222011/51618214-8addd680-1f36-11e9-8691-ac32eb021048.png)

**Comment by SashaKononenko** [comment]
має бути назразок такого 
![image](https://user-images.githubusercontent.com/22222011/51618246-9df0a680-1f36-11e9-8321-e47eaa464d4b.png)

**Comment by gzaspa** [comment]
так, правильно. Єдине, бажано англійський текст поставити з нового рядка
