### ISSUE TITLE
Працівник деканату може знайти студента серед усіх відрахованих

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#174]
На вкладці відрахованих студентів є поле (поля) пошуку, за якими шукатиметься студент серед усіх відрахованих. Для пошуку використовувати поля прізвище, ім'я, початкова дата пошуку, кінцева дата пошуку. Зробити два режими роботи вікна: "відраховані з можливістю перегляду детальних даних, поновлення та формування академдовідки" та "всі відраховані з можливістю перегляду детальних даних".

**Comment by NicolasFaydik** [comment]
Додатково зробити вікно з історією відрахування і поновлення конкретного студента.
