### ISSUE TITLE
Працівник деканату може сформувати список предметів академрізниці для студентів, що поновлюються або переходять з інших навчальних закладів

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#180]
Для такого студента потрібно знайти предмети попередніх семестрів його групи, в яких оцінка для нього null, і вивести у вигляді таблиці. Над таблицею: ПІБ студента, група, слово "Академрізниця", в таблиці: 1 семестр: назва предмету, години, вид контролю; 2 семестр: назва предмету, години, вид контролю і так пішло далі.

**Comment by SashaKononenko** [comment]
Ось так?
[список предметів академрізниці.docx](https://github.com/chdtu-fitis/deanoffice-backend/files/2827861/default.docx)

**Comment by SashaKononenko** [comment]
Порядок важливий? наприклад щоб екзамини були вище, потім курсові, а потім заліки?

**Comment by SashaKononenko** [comment]
[response.docx](https://github.com/chdtu-fitis/deanoffice-backend/files/2857719/response.docx)

Запушив, **покищо рефакторинг не робив**, хотів би шоб ви просто подивилися наскільки це відповідає необхідному результату

**Comment by gzaspa** [comment]
Так, форма правильна, єдине, що потрібно покращити - це зробити колонку назв предметів ширшою, а інші колонки, відповідно, вужчими
