### ISSUE TITLE
Працівник деканату може сформувати форму журналу оцінок 

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#203]
Таку форму використовують деякі деканати. В зразку форма для заочників, там предмети зразу за два семестри; для стаціонару повинні бути предмети одного семестру на одній сторінці.
[Зразок журнала успішності ФКТМД.docx](https://github.com/chdtu-fitis/deanoffice-backend/files/2885199/default.docx)
Думаю, можна використати напрацювання, зроблені при формуванні інших виписок, зокрема списків студентів та списків предметів для журналів деканату. Як мінімум, сервіси для вичитування інформації там точно готові.

**Comment by SashaKononenko** [comment]
побачив

**Comment by gzaspa** [comment]
[Результати заліків та іспитів 2018-2019 н.р.-скор.docx](https://github.com/chdtu-fitis/deanoffice-backend/files/2888685/2018-2019.-.docx)
Це для стаціонару

**Comment by SashaKononenko** [comment]
А які вхідні данні в цій задачі?

**Comment by gzaspa** [comment]
Вхідні дані - сама форма, групи, предмети та студенти.

**Comment by SashaKononenko** [comment]
Я маю наувазі в запиті які параметри передаються?

**Comment by SashaKononenko** [comment]
В "Зразок журнала успішності ФКТМД.docx" який ви скинули, там одна група, в іншому файлі декілька груп.

**Comment by gzaspa** [comment]
Думаю, краще всього - це курс і форма навчання (денна, заочна)

**Comment by SashaKononenko** [comment]
А семестр?

**Comment by gzaspa** [comment]
Так, точно, і семестр - перший або другий

**Comment by SashaKononenko** [comment]
Я тут зрозумів, що ще Degree треба передавати

**Comment by gzaspa** [comment]
Done
