### ISSUE TITLE
Помилка в додатку до диплому: непраильний "Description of Learning Outcomes"

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#21]
В додатку в розділі "Description of Learning Outcomes - Knowledge and understanding" замість англійського тексту український. Закликаю перевіряти роботу програми після внесення змін.

**Comment by ValentynTulub** [comment]
Так, дійсно, від назви плейсхолдера відірвалось слово Eng. Зараз виправлю.

**Comment by gzaspa** [comment]
Виправлено.
