### ISSUE TITLE
Працівник деканату може отримати список студентів вказаних випускних груп

### ISSUE THREAD

**Issue by Alex222438** [chdtu-fitis/deanoffice-backend#214]
Дана функція потрібна для виконання операції "Завершення навчального року"
На вході отримується список id груп. 
Валідація: потрібно перевіряти, чи всі групи у списку є випускними
Повертається: Map, ключ - назва групи, значення - список активних студентів цієї групи (поля: прізвище, ім'я, по батькові, номер диплома)

**Comment by gzaspa** [comment]
Done
