### ISSUE TITLE
Адміністратор може знайти всі назви предметів, які являють собою фактично одну назву.

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#228]
В системі є немало випадків, коли є декілька записів у таблиці course_name, які являють собою фактично одну назву, - буває, що в кінці стоїть пропуск, або всередині назви десь два пропуски, або помилка, або вкралась англійська буква. Приклад - можна сформувати додаток для диплому для групи ПЛ-51 і подивитись - там предмет "Граматика першої мови" зустрінеться двічі, хоча програма повинна злити його в один - причина в тому, що в кінці однієї з назв стоїть пропуск.

**Comment by markinger** [comment]
Done

**Comment by markinger** [comment]
Done
