### ISSUE TITLE
Працівник деканату може сформувати відомість для студентів-випускників, що формується перед захистами випускних робіт або держіспитами

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#244]
Повна назва документу: ВІДОМІСТЬ навчальних досягнень здобувачів вищої освіти, які виконали усі вимоги навчального плану освітньої програми за період навчання
[Відомість-на захисти.docx](https://github.com/chdtu-fitis/deanoffice-backend/files/3022031/-.docx)
Документ формується для випускних груп. Форма документа - pdf.

**Comment by markinger** [comment]
Done
