### ISSUE TITLE
Працівник деканату може сформувати документ з аркушем успішності студента ("бігунком")

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#279]
![image](https://user-images.githubusercontent.com/16689707/57630757-df20cb00-75a6-11e9-90bf-9f75af6c3ba9.png)
![image](https://user-images.githubusercontent.com/16689707/57630831-feb7f380-75a6-11e9-8c52-927a0bbed545.png)
Відповідні поля повинні бути заповнені відповідними даними про предмет, студента, викладача тощо.

**Comment by SashaKononenko** [comment]
1) Як цей документ взагалі виглядає? оці картинки це документ з двох сторін, чи просто вижче і нежче?

**Comment by gzaspa** [comment]
нова форма
![IMG_20190524_142007](https://user-images.githubusercontent.com/16689707/58324581-ed38dc00-7e2f-11e9-8c40-00a3925c0edc.jpg)
![IMG_20190524_142016](https://user-images.githubusercontent.com/16689707/58324583-ed38dc00-7e2f-11e9-8300-9320caaf9909.jpg)

**Comment by gzaspa** [comment]
Форма "бігунка" не зовсім точна

**Comment by gzaspa** [comment]
Є файл з новою формою бігунка, там можна подивитись точні розміри
[Аркуш успішності.docx](https://github.com/chdtu-fitis/deanoffice-backend/files/3685002/default.docx)
