### ISSUE TITLE
Працівник деканату може у виписках в особові справи зробити титульну сторінку, а також останню сторінку з темою дипломної, результатами захисту, держіспитами і т.д.

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#308]

**Comment by El-Treshka** [comment]
Титульна та кінцева сторінки.
**P.S. Не остаточний варіант, може змінитися.**
![photo_2019-09-30_12-18-01](https://user-images.githubusercontent.com/32441160/65973079-6c3fc000-e473-11e9-9443-c570c40d5985.jpg)
![photo_2019-09-30_12-18-14](https://user-images.githubusercontent.com/32441160/65973080-6c3fc000-e473-11e9-9a5c-02b0e9a57d63.jpg)

**Comment by gzaspa** [comment]
Є нова форма документу, нам потрібна з нього тільки перша та остання сторінки
[Навчальна карта студента.docx](https://github.com/chdtu-fitis/deanoffice-backend/files/3702372/default.docx)
