### ISSUE TITLE
Працівник деканату може сформувати заліково-екзаменаційні відомості для вибраних групи і предметів (епік #17)

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#33]

**Comment by gzaspa** [comment]
ДУЖЕ важливо робити перевірку функціоналу з різними даними. Наприклад, формування відомості для тих предметів, для яких не встановлено ті поля, які не є NOT NULL. Наприклад, для предметів з не встановленою датою екзамену функція валиться

**Comment by TarasTurchenko** [comment]
Такі речі саме і потрібно провіряти тестами

**Comment by gzaspa** [comment]
Done.
