### ISSUE TITLE
Працівник деканату може вибирати групу, для якої сформувати документ зі списком предметів для журналу відомостей свого факультету (епік #35)

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#40]
Працюючи з даним компонентом, користувач повинен мати можливість вибрати курс, денну/заочну форму і тоді відібрані групи

**Comment by SashaKononenko** [comment]
Як мені правильно написати курс в коді, наприклад getGroupsByTuitionFormAnd...... і як тут написти?

**Comment by gzaspa** [comment]
Year

**Comment by gzaspa** [comment]
![default](https://user-images.githubusercontent.com/16689707/37645129-a14034a0-2c2e-11e8-85be-88eff01c3334.png)
Скріншот зі старої програми

**Comment by gzaspa** [comment]
Реалізовано в інших issues.
