### ISSUE TITLE
 Працівник деканату може сформувати документ зі списком предметів для журналу відомостей свого факультету

### ISSUE THREAD

**Issue by gzaspa** [chdtu-fitis/deanoffice-backend#57]

**Comment by SashaKononenko** [comment]
Щойно закомітив гілку groups_for_dean_worker#57. На даний момент можна зробити список предметів лише для однієї групи в одному семестрі. Прошу перверіти результат щоб я міг далі продовжувати роботу. І особливо прошу звернути увагу на назви класів/пакетів, тому що мені вони не здаються дуже вдалими.

**Comment by TarasTurchenko** [comment]
Загальна рекомендація: потрібно частіше робити мерж **з** девелопмента в свою гілку. Тоді менш болючим буде мерж **в** девелопмент

**Comment by gzaspa** [comment]
Потрібно уникати будь-якої транслітерації з української в коді, писати англійські назви. Не потрібно ставити дату в назву файлу. Всередині файлу - кирилічні текст, в тому числі назва групи.

**Comment by gzaspa** [comment]
CourseReport - сумнівної потрібності клас

**Comment by gzaspa** [comment]
я злив з development і зробив перейменування та виправлення. Можна продовжувати.

**Comment by SashaKononenko** [comment]
Цей issues ще не закінчений, нажаль я досі не зміг реалізувати одну функцію

**Comment by SashaKononenko** [comment]
Я зробив, але є дуже дивна проблема, я наприклад можу свормувати відомість для 3 курсу 1,2 і 5 симестрів і все правильно формується, а для інших не можу. І я незнаю в чому проблема таке враження що щось не так з БД

**Comment by gzaspa** [comment]
Те, що можу сказати нашвидкоруч - в нас зараз працює вже перегляд предметів для груп, за допомогою цієї функції можна дивитись, які предмети для якої групи в якому семестрі призначені і можна легко перевірити Вашу гіпотезу

**Comment by SashaKononenko** [comment]
я частково знайшов помилку. В таблиці coursesforgroup поле teacher_id незаповненне

**Comment by SashaKononenko** [comment]
Інколи не заповнене

**Comment by gzaspa** [comment]
Дане поле може бути не заповнене, це особливість предметної області. В БД там не стоїть not null, значить, значення може не бути і це потрібно брати до уваги.

**Comment by SashaKononenko** [comment]
Тепер я вже виправив, все працює так як треба

**Comment by SashaKononenko** [comment]
Все нормально працювало. Сьогодні зробив мерж з гілки development, бо треба ж гілку в актуальному стані тримати, і все зламалося  знову

**Comment by gzaspa** [comment]
Потрібно відкотитись на одну транзакцію назад, я змерджу тоді в development

**Comment by SashaKononenko** [comment]
А як це правильно зробити? Я можу в IDEA відкотитися до версії яка правціювала, і що потім зробити?

**Comment by TarasTurchenko** [comment]
Якщо ти вмержив девелопмент і в тебе зламалось щось, то це потрвбно виправляти,  бо тоді це зламається тоді,  коли твою гілку в девелопмент вмержать

**Comment by gzaspa** [comment]
Після того, як відкотились, потрібно зробити push

**Comment by SashaKononenko** [comment]
Я зробив push, але коли знов оновлюю гілку вона всеодно не працює. Тобто мабуть гілка не відкотилася назат як треба було

**Comment by gzaspa** [comment]
Уточнююча задача: зробити, щоб документ робився для всього курсу, а не окремої групи

**Comment by SashaKononenko** [comment]
Що мається наувазі під курсом? Ми ж можемо вже зараз зробити документ не тільки для конкретної групи, а і для конкретного курсу. Тобто ми вказуємо курс, degree і семестр.
`@GetMapping("/year/{yearId}/degree/{degreeId}")
    public ResponseEntity<Resource> generateForYear(@PathVariable Integer yearId,
                                                    @PathVariable Integer degreeId,
                                                    @RequestParam("semester") int semester,
                                                    @CurrentUser ApplicationUser user)  {`

**Comment by gzaspa** [comment]
Так, є таке і воно працює. 1. Потрібно перевірити правильність формування цього документу. 2. Потрібно зробити, щоб дата відображалась в правильному форматі. 3. Потрібно, щоб для курсових робіт і проектів замість годин ставило КР і КП. 4. Потрібно перевірити, чи правильні розміри колонок таблиці.

**Comment by gzaspa** [comment]
5. Потрібно поставити перевірку на правильність факультету, як у попередньом методі

**Comment by SashaKononenko** [comment]
- формат дати виправив

**Comment by SashaKononenko** [comment]
-

**Comment by SashaKononenko** [comment]
Дані в документ виводяться правильні, те що в базі те і в документі

**Comment by gzaspa** [comment]
В методі контролера generateForGroup() є перевірка на правильність факультету

**Comment by SashaKononenko** [comment]
Пробачте що так довго нічого не робив, я нарешті повернувся до роботи. І пришов до висновку що перевірка на правильність факультету в методі generateForYear() є не доцільною, принаймі я не розумію її не обхідності. Оскільки в цьому методі робимо документи для певного курсу **всього** факультету. І передаємо id факультету як параметр.
`File reportsJournal = reportsCoursesService.prepareReportForYear(degreeId,yearId, semester,**user.getFaculty().getId());**`

**Comment by gzaspa** [comment]
Так, саме про це я писав  у слеку на Ваше питання.
"Якщо мова йде про те, що потрібно сформувати документ для певного курсу (першого, другого і т.д.), то задача перевірки факультету є не актуальною, тому що там не передається параметром контролера ніякий id, з яким можуть бути такі проблеми."

**Comment by gzaspa** [comment]
Потрібно зробити, щоб сортування в таблицях було за датою. Якщо дата null, то такі предмети повинні йти в кінці, сортування за алфавітом

**Comment by SashaKononenko** [comment]
Як зміг реалізував алгоритм сотування, але  можливо можна якось і простіше

**Comment by gzaspa** [comment]
Done
